apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker2-deployment
  labels:
    app: nginx-worker2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-worker2
  template:
    metadata:
      labels:
        app: nginx-worker2
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: worker2-service
spec:
  selector:
    app: nginx-worker2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
