apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-worker01
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-worker01
  template:
    metadata:
      labels:
        app: nginx-worker01
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k8s-worker01
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-worker02
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-worker02
  template:
    metadata:
      labels:
        app: nginx-worker02
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k8s-worker02
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
