apiVersion: v1
kind: Service
metadata:
  name: nginx-service-worker01
  namespace: default
spec:
  type: NodePort
  selector:
    app: nginx-worker01
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service-worker02
  namespace: default
spec:
  type: NodePort
  selector:
    app: nginx-worker02
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002